services:
  backend:
    image: ${DOCKER_REGISTRY-}autoshopwebapi
    build:
      context: .
      dockerfile: AutoShopWebAPI/Dockerfile

  client:
    image: client
    build:
      context: ./client
      dockerfile: Dockerfile
  
  proxy:
    image: nginx:mainline
    