// <auto-generated />
using DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoShop.Migrations
{
    [DbContext(typeof(CarContext))]
    [Migration("20240906195803_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AutoShop.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Color = "White",
                            Model = "Toyota Camry",
                            Year = 2020
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Color = "Blue",
                            Model = "Honda Civic",
                            Year = 2019
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Color = "Black",
                            Model = "Ford Explorer",
                            Year = 2021
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Color = "Red",
                            Model = "Chevrolet Tahoe",
                            Year = 2022
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Color = "Silver",
                            Model = "BMW 2 Series",
                            Year = 2018
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Color = "Gray",
                            Model = "Mercedes-Benz C-Class",
                            Year = 2017
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 4,
                            Color = "Green",
                            Model = "Mazda MX-5",
                            Year = 2021
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            Color = "Yellow",
                            Model = "Ford Mustang",
                            Year = 2020
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 5,
                            Color = "White",
                            Model = "Volkswagen Golf",
                            Year = 2019
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 5,
                            Color = "Black",
                            Model = "Honda Fit",
                            Year = 2020
                        });
                });

            modelBuilder.Entity("AutoShop.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Standard 4-door passenger cars",
                            Name = "Sedan"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Sport Utility Vehicles",
                            Name = "SUV"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Two-door sports cars",
                            Name = "Coupe"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Cars with retractable roofs",
                            Name = "Convertible"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Compact cars with hatch-style trunk",
                            Name = "Hatchback"
                        });
                });

            modelBuilder.Entity("AutoShop.Models.Car", b =>
                {
                    b.HasOne("AutoShop.Models.Category", "Category")
                        .WithMany("Cars")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("AutoShop.Models.Category", b =>
                {
                    b.Navigation("Cars");
                });
#pragma warning restore 612, 618
        }
    }
}
